name: A TO A:GH_PAGES
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.VUEAD }} # VUEAD 是我的 secret 名称，需要替换成你的
        # 你要操作的目标仓库，注意：是项目仓库名
        TARGET_REPO: longweixia/vue-ad
        # 构建结果存储的分支
        TARGET_BRANCH: master
        # 要使用的构建命令
        BUILD_SCRIPT: npm install && npm run build # 下载依赖 打包项目
        # 构建结果存储目录，dist里面会有index.html，如果没有这个文件，显示不了，可在本地构建后去校验
        BUILD_DIR: dist
# # name: A TO A:GH_PAGES
# # on: # 监听 master 分支上的 push 事件
# #   push:
# #     branches:
# #       - master
# # jobs: # 开始工作
# #   build-and-deploy:
# #     runs-on: ubuntu-latest # 构建环境使用 ubuntu，工作流程要运行在什么操作系统上
# #     steps: # 执行步骤 
# #     - name: actions/checkout@v1 # 小步骤的名称
# #       uses: actions/checkout@master # 小步骤使用的 actions 库名称或路径，Github Actions 允许你使用别人写好的 Actions 库。

# #     - name: Build and Deploy
# #       uses: jenkey2011/vuepress-deploy@master
# #       env: # 设置与小步骤相关的环境变量。
# #         ACCESS_TOKEN: ${{ secrets.VUEAD }} # VUE_ADMIN_TEMPLATE 是我的 secret 名称，需要替换成你的
# #         # 你要操作的目标仓库
# #         TARGET_REPO: longweixia/vue-ad
# #         # 构建结果存储的分支
# #         TARGET_BRANCH: master
# #         # 要使用的构建命令
# #         BUILD_SCRIPT: npm install && npm run build # 下载依赖 打包项目，小步骤要执行的 shell 命令。
# #         # 构建结果存储目录
# #         BUILD_DIR: dist
# name: Build app and deploy to aliyun
# on:
#   #监听push操作
#   push:
#     branches:
#       # master分支，你也可以改成其他分支
#       - master
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1 # actions/checkout@v1 库克隆代码到 ubuntu 上
#     - name: Install Node.js
#       uses: actions/setup-node@v1 # actions/setup-node@v1 库安装 nodejs
#       with: # with 提供了一个参数 node-version 表示要安装的 nodejs 版本。
#         node-version: '12.16.2'
#     - name: Install npm dependencies
#       run: npm install # ubuntu 的 shell 上执行 npm install 下载依赖。
#     - name: Run build task
#       run: npm run build # 执行 npm run build 打包项目
#     - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@v2.1.5 # easingthemes/ssh-deploy@v2.1.5 库，这个库的作用就是用 SSH 的方式远程登录到腾讯云服务器，将打包好的文件夹复制到腾讯云指定的目录上。
#       env:
#           SSH_PRIVATE_KEY: ${{ secrets.TX }} # 腾讯云密钥对中的私钥（需要你提前写在 github secrets 上），
#           ARGS: '-rltgoDzvO --delete' # 没仔细研究，我猜是复制完文件就删除掉
#           SOURCE: dist # 这是要复制到腾讯云静态服务器的文件夹名称
#           REMOTE_HOST: '81.71.118.241' # 你的腾讯云公网地址
#           REMOTE_USER: root # 腾讯云登录后默认为 root 用户，并且所在文件夹为 root
#           TARGET: dist # 打包后的 dist 文件夹将放在 /root/node-server
